version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          name: Newman Run
          collection: ./tests/CircleCI\ newman\ orb\ test.postman_collection.json
          additional-options: -r cli,junit
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/newman
            cp ./newman/newman-run-report-*.xml ~/test-results/newman/
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/newman


